[project]
name = "save-file-to-s3"
version = "0.1.0"
description = "Save file to S3"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modal>=0.62.0",
    "pydantic>=2.0.0",
    "fastapi>=0.115.0",
]
